#docker build -t semgrep/ocaml-5.3.0-semgrep-dev-base -f Dockerfile.dev .
FROM semgrep/ocaml-5.3.0-semgrep

# dev packages for IDEs
RUN opam update && \
    opam install lsp dune ocaml-lsp-server utop odoc ocamlformat -y && \
    opam clean --download-cache --repo-cache --all-switches
